### ISSUE TITLE
Remove security related discussion (and that related to HTTPS)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/data-catalog-spec#8]
See comments from Will Pugh of Socrata: http://lists.okfn.org/pipermail/data-catalogs/2012-November/000097.html

> ... I would say that the standard sits above HTTP/HTTPS and that which one is used is orthogonal.  Providers that want to provide protection are free to use HTTPS, but providers are not compelled to.

**Comment by rufuspollock** [comment]
I'm +1

**Comment by chrismetcalf** [comment]
+1 for me too

**Comment by pietercolpaert** [comment]
+1
